steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: [ "-m", "rsync", "gs://qix-maps/", "shared/" ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/qix-tf2', '.' ]
images:
- 'gcr.io/$PROJECT_ID/qix-tf2'