steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', '-r', 'gs://qix-maps/', '/workspace/shared/']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/qix-tf2', '.' ]
images:
- 'gcr.io/$PROJECT_ID/qix-tf2'
timeout: 30m